src/map/urls.py
from rest_framework import routers
from django.urls import path
from .api import (
    AreeProtetteCheckListViewSet, AreeProtetteViewSet,ComuniViewSet, ObservationChecklistViewSet,
    ProvinceViewSet, ComuniViewSet, ObservationChecklistDetailedViewSet
)
from .views import AreeAutocomplete, ComuniAutocomplete

router = routers.DefaultRouter()
router.register(r'province', ProvinceViewSet)
router.register(r'comuni', ComuniViewSet)
router.register(r'areeprotette', AreeProtetteViewSet)
router.register(r'aree-protette-check', AreeProtetteCheckListViewSet,basename='aree-protette-check')
router.register(r'observations-taxon-check', ObservationChecklistViewSet,basename='observations-taxon-check')
router.register(r'observations-taxon-detailed-check', ObservationChecklistDetailedViewSet,basename='observations-taxon-detailed-check')


urlpatterns = [    
    path('aree-autocomplete',AreeAutocomplete.as_view(),name="aree-autocomplete"),
    path('comuni-autocomplete/',ComuniAutocomplete.as_view(),name='comuni-autocomplete'),

]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

src/profiles/models.py
from __future__ import unicode_literals
import uuid
from django.db import models
from django.conf import settings

from biodiv.models import Institution
from django.core.exceptions import ValidationError


class BaseProfile(models.Model):
    """
    Profilo base
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True
    )
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)

    picture = models.ImageField(
        "Immagine del profilo", upload_to="profile_pics/%Y-%m-%d/", null=True, blank=True
    )
    motivation = models.CharField("Motivo d'iscrizione al Portale", max_length=1000, blank=True,default='')
    bio = models.CharField("Breve bio", max_length=200, blank=True, null=True)
    declared_institution = models.ForeignKey(
        Institution, models.CASCADE, blank=True, null=True, verbose_name='Istituzione di appartenenza dichiarata')
    declared_institution_nonpresent = models.CharField('Istituzione di appartenenza se non presente nel menu',blank=True, null=True,max_length=300)
    email_verified = models.BooleanField("Email verificata", default=False)
    validation_referee = models.BooleanField("Referente per la validazione dei dati", default=False)
    institution_verified = models.BooleanField("Istituzione verificata", default=False)

    class Meta:
        abstract = True

    def clean(self):
        super(BaseProfile, self).clean()

        if self.declared_institution and self.declared_institution_nonpresent:
            raise ValidationError('Specificare la propria istituzione una sola volta!')



# @python_2_unicode_compatible
class Profile(BaseProfile):
    """
    Profilo completo
    """

    def __str__(self):
        return "Profilo di {}".format(self.user)

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from . import models

from django.urls import reverse

User = get_user_model()


class UserForm(forms.ModelForm):
    """
    Form per i dettagli dell'utente base
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(Field("name"))

    class Meta:
        model = User
        fields = ["name"]


class ProfileForm(forms.ModelForm):
    """
    Form per i dettagli del profilo

    .. image:: ../../_static/manual/biostream_24.png
        :width: 400
        :alt: Immagine del form di dettaglio profilo

    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field("picture"),
            Field("motivation"),
            Field("declared_institution"),
            Field("bio"),
            Div(Submit("update", "Aggiorna", css_class="btn-success"),
                HTML(
                '<a class="btn btn-default" href="{}">Cambia password</a>'.format(
                    reverse("accounts:password-change")
                )
            ), css_class="form-row")
        )

    class Meta:
        model = models.Profile
        fields = ["picture", "motivation","bio", "declared_institution"]

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    """
    Vista per mostrare i dettagli del profilo
    """
    template_name = "profiles/show_profile.html"
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get("slug")
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super().get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    """
    Vista per modificare i dettagli del profilo
    """
    template_name = "profiles/edit_profile.html"
    http_method_names = ["get", "post"]

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(
            request.POST, request.FILES, instance=user.profile
        )
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(
                request,
                "C'è stato un problema nel form. " "Si prega di controllare i dettagli.",
            )
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super().get(request, user_form=user_form, profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Dettagli del profilo salvati!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profilo{% endblock %}

{% block main_menu %}
    {% include "_navbar.html" with active_link="servizi" %}
{% endblock main_menu %}

{% block centered_container %}

<div class="container">
  <div class="container profile-head">
  <h1>Edita profilo - {{ user.get_full_name }}</h1>
  </div>
  <br>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Informazioni personali</h3>
      <form enctype="multipart/form-data" method="post">
      {% crispy user_form %}
      {% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
{% endblock centered_container %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load static %}
{% load thumbnail %}

{% block main_menu %}
    {% include "_navbar.html" %}
{% endblock main_menu %}

{% block title %}{{ block.super }}Profilo{% endblock %}

{% block centered_container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edita profilo</a>
      <a href="{% url 'datarequests-list' %}" class="btn btn-primary">Richieste dati</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-5">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profilo</li>
        <li class="list-group-item"><span class="pull-left"><strong>Email: </strong> </span> {{ show_user.email|default:"Nessuna mail fornita" }}{% if show_user.profile.email_verified %} <span class="pull-right"><i class="fas fa-check-circle" title="Indirizzo mail verificato">{% else %}<i class="fas fa-times-circle" title="Indirizzo mail non verificato">{% endif %}</i></span></li>
        <li class="list-group-item"><span class="pull-left"><strong>Istituzione: </strong></span> {{ show_user.profile.declared_institution.institution_name|default:"NA" }} ({{ show_user.profile.declared_institution.province|default:"NA" }})
        {% if show_user.profile.institution_verified %} <span class="pull-right"><i class="fas fa-check-circle" title="Istituzione verificata">{% else %}<i class="fas fa-times-circle" title="Istituzione non verificata">{% endif %}</i></span></li>
        <li class="list-group-item"><span class="pull-left"><strong>Registrazione: </strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item"><span class="pull-left"><strong>Ultimo login: </strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-7">
      <div class="panel panel-default">
        <div class="panel-heading">
	  {% if show_user.profile.slug %}
	    <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    	<span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    	<span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
	  {% else %}
		<a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>
	  {% endif %}
	</div>
        <div class="panel-body">
	  <strong>Bio</strong>: {{ show_user.profile.bio }}
	</div>
      </div>
    </div>
  </div>
</div>

{% endblock centered_container %}