src/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path('password-reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password-reset-confirm')
    # url(
    #    r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
    #    views.PasswordResetConfirmView.as_view(),
    #    name="password-reset-confirm",
    # ),
]

src/map/urls.py
from rest_framework import routers
from django.urls import path
from .api import (
    AreeProtetteCheckListViewSet, AreeProtetteViewSet,ComuniViewSet, ObservationChecklistViewSet,
    ProvinceViewSet, ComuniViewSet, ObservationChecklistDetailedViewSet
)
from .views import AreeAutocomplete, ComuniAutocomplete

router = routers.DefaultRouter()
router.register(r'province', ProvinceViewSet)
router.register(r'comuni', ComuniViewSet)
router.register(r'areeprotette', AreeProtetteViewSet)
router.register(r'aree-protette-check', AreeProtetteCheckListViewSet,basename='aree-protette-check')
router.register(r'observations-taxon-check', ObservationChecklistViewSet,basename='observations-taxon-check')
router.register(r'observations-taxon-detailed-check', ObservationChecklistDetailedViewSet,basename='observations-taxon-detailed-check')


urlpatterns = [    
    path('aree-autocomplete',AreeAutocomplete.as_view(),name="aree-autocomplete"),
    path('comuni-autocomplete/',ComuniAutocomplete.as_view(),name='comuni-autocomplete'),

]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

src/templates/documentation/documentation_base.html
{% extends 'base_nologo.html' %}

{% load static %}

{% block main_menu %}
    {% include "_navbar.html" with active_link="documentation" %}
    <style>
        .img-doc-wide {
            width: 60%;
            border: 1px solid black;
        }
        .img-doc-long {
            width: 30%;
            border: 1px solid black;
        }
    </style>    
{% endblock main_menu %}

{% block centered_container %}

<h1>Documentazione</h1>
{% block documentation_detail %}
Benvenuti nel Portale BioSTREAM! Questa guida vi guiderà attraverso alcune delle principali <em>feature</em> del sito web.

<h3>Osservazioni, Fornitori, Gestori</h3>
Il Portale si basa su <em>osservazioni</em> di fauna e flora di qualsiasi grado di protezione, provenienti da <a href="{% url 'catalogo'%}">svariati dataset</a> forniti dalle Istituzioni (d'ora in avanti, <code>fornitori</code>) partecipanti al Progetto: ogni <code>fornitore</code> decide tramite un apposito accordo (<a href="{{MEDIA_URL}}docs/modello_di_accordo.doc">modello</a>) i termini relativi alla fornitura delle proprie basi dati, tra i quali:
<ul>
    <li><strong>metodi</strong>, ovvero, se i dataset devono venire caricati direttamente all'interno del Portale BioSTREAM o se automaticamente recuperati da una fonte accessibile via web che il <code>fornitore</code> mette a disposizione (quest'ultima procedura è per ora attiva per due sole fonti: i dati MUSE - Museo delle Scienze di Trento e i dati <a href="www.inaturalist.org">iNaturalist</a>);</li>
    <li><strong>precisione spaziale delle osservazioni</strong>, per quanto quest'ultima sia desiderabilmente la massima disponibile: il Portale mette infatti a disposizione precise funzionalità di diluizione della precisione per utenti non autenticati e per <em>fornitori</em> che non hanno esplicita autorizzazione alla visualizzazione da parte di altri <em>fornitori</em>.</li>
</ul>

Il gruppo di conduzione del portale (<code>gestori</code>) si preoccupa di intessere le necessarie relazioni con i <code>fornitori</code>, dello sviluppo e della regolare manutenzione dello stesso e della mobilizzazione ai fini BioSTREAM delle proprie banche dati. Per assicurare la compatibilità con il Portale, i dati vengono preventivamente standardizzati <a href="{% static 'standard_inserimento_biostream.pdf' %}">secondo un apposito protocollo</a>. 

<h3><a href="{% url 'home'%}">Homepage</a></h3>
<figure>
<img class ="img-doc-wide" src="{% static 'site/img/manual/biostream_1.png'%}"></img>
<figcaption>Mappa di densità delle osservazioni entro BioSTREAM</figcaption>
</figure>
La pagina presenta le maggiori funzionalità del portale assieme a brevi statistiche riassuntive aggiornate in tempo reale: tali statistiche includono una cartografia che mostra con una scala di colori automaticamente riscalata dal numero massimo al numero minimo la densità di osservazioni rispetto ad una griglia regolare di 10x10<code>km</code> entro il database BIoSTREAM.
La home rimanda inoltre alle tre principali funzionalità del portale, ovvero:

<ul>
    <li><strong><a href="{% url 'gis'%}">WebGIS</a></strong>, strumento di consultazione delle osservazioni su mappa;</li>
    <li><strong><a href="{% url 'catalogo'%}">GeoServer</a></strong>, utile alla fornitura delle cartografie di sfondo (e.g., Habitat Natura 2000) e all'interfaccia con software GIS per il tramite di servizi <code>WMS</code>/<code>WFS</code>;</li>
    <li><strong><a href="{% url 'table-specie'%}">Consultazioni di dettaglio</a></strong>, che visualizza informazioni riguardo gli attributi delle varie osservazioni memorizzate</li>
</ul>

Entro l'amministrazione del profilo 

Le funzionalità più ampie ed interessanti sono racchiuse entro le pagine <a href="{% url 'documentation_gis'%}">WebGIS</a> e consultazioni di dettaglio / checklist<a href="{% url 'documentation_checklist'%}"></a> e nella domanda di <a href="{% url 'documentation_datarequest' %}">accesso dati di dettaglio</a>, alla documentazione delle quali i link precedenti e i menu nella barra di navigazione rimandano.

<h3><a href="{% url 'profiles:show_self'%}">Profilo</a></h3>
<figure>
<img class ="img-doc-wide" src="{% static 'site/img/manual/biostream_23.png'%}"></img>
<figcaption>Profilo esempio di un utente</figcaption>
</figure>

Completata la <a href="{% url 'accounts:signup'%}">prima registrazione</a> dell'utente entro il portale, l'utente ha la possibilità di completare il proprio profilo con alcune informazioni di base, cliccando sul pulsante <em><a href="{% url 'profiles:edit_self' %}">edita il profilo</a></em>. Particolarmente importanti sono i campi:
<ul>
    <li><strong>Istituzione di appartenenza dichiarata</strong>: l'utente seleziona tra quelle disponibili, e se legittima, gli amministratori di sistema ne associano il profilo a tale istituzione. Una volta completato questo processo l'utente visualizzerà i dati forniti dall'istituzione alla quale viene associato <em>alla massima precisione disponibile</em>, così come i dataset dei fornitori che hanno esplicitamente concesso la visualizzazione precisa all'istituzione legata all'utente. Le rimanenti osservazioni restano vincolate alle normali procedure di tutela del portale;</li>
    <li><strong>Breve bio</strong>: descrizione dell'utente utile a valutare da parte degli amministratori l'istituzione di appartenenza dichiarata.</li>
</ul>

Nel caso in cui l'utente non abbia un profilo di amministrazione, gli viene data la possibilità di <a href="{% url 'documentation_datarequest'%}">richiedere la visualizzazione per dati di dettaglio</a>.

{%endblock documentation_detail%}

{% endblock centered_container %}

src/templates/documentation/documentation_catalog.html
{% extends 'documentation/documentation_base.html' %}

{% block documentation_detail %}
{%endblock documentation_detail%}

src/templates/documentation/documentation_checklist.html
{% extends 'documentation/documentation_base.html' %}
{% load static %}

{% block documentation_detail %}
<h3>Checklist</h3>
La consultazione entro questa pagina avviene in maniera molto simile allo strumento "<a href="{% url 'documentation_gis'%}#areaquery">Cerca per area disegnata</a>" nella pagina WebGIS, ma fornisce informazioni riassuntive ugualmente scaricabili in formato <code>csv</code> sulle specie e sugli habitat presenti entro una certa area selezionata/disegnata.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_28.png'%}"></img>
</figure>

A seconda delle dimensioni dell'area, l'interrogazione può talvolta risultare relativamente lenta, ma in ogni caso sempre inferiore ai 30 secondi nel tempo di restituzione.

L'utente ha a disposizione due funzionalità di ricerca:
<ul>
    <li>la prima, attivata semplicmente selezionando una delle aree protette entro l'area del Progetto dal menu a tendina (è possibile cercare una particolare area protetta per codice o nome) gli permette di ottenere le informazioni entro i confini di quella specifica area
    <figure>
        <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_30.png'%}"></img>
    </figure>
    </li>
    <li>
    nella seconda, può disegnare un'area qualsiasi, ed ottenere le stesse informazioni di cui sopra.
    <figure>
        <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_32.png'%}"></img>
    </figure>
    </li>
</ul>

Tutte le informazioni restituite sono scaricabili premendo il bottone di download, e dettagliano:

<ul>
    <li>le varie specie presenti nell'area, divise per classe;</li>
    <li>gli habitat presenti nell'area, dettagli dei quali sono visualizzabili come nella <a href="{% url 'documentation_gis'%}#layersfondo">pagina WebGIS</a></li>
</ul>
{%endblock documentation_detail%}

src/templates/documentation/documentation_datarequest.html
{% extends 'documentation/documentation_base.html' %}
{% load static %}

{% block documentation_detail %}
<h3>Richieste dati</h3>
Gli utenti non amministratori che desiderano ottenere informazioni più precise rispetto ad una certa area possono richiederle utilizzando l'apposito tool <a href="{% url 'profiles:show_self'%}">entro il loro profilo</a>.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_23.png'%}"></img>
</figure>
Cliccando su "richiesta dati" all'utente viene presentato un semplice form ove va specificato:
<ul>
    <li>di dettagliare le motivazioni della richiesta;</li>
    <li>di disegnare l'area per la quale si richiedono i dati precisi;</li>
    <li>di indicare se si desiderano dati precisi per sole specie in Direttiva Habitat.</li>
</li>
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_25.png'%}"></img>
</figure>

Una volta completato ed inviato il form, il sistema genera al volo i dettagli utili agli amministratori di sistema per valutarla: tale generazione può richiedere qualche secondo. 
Una volta completato il processo, l'utente viene rimandato alla pagina dove vengono elencate tutte le richieste.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_33.png'%}"></img>
</figure>

Ogni richiesta presenta, oltre all'inquadramento in mappa della stessa, svariati dettagli:

<ul>
    <li>l'elenco dei <code>fornitori</code> che devono approvare la richiesta, con segnato lo <em>status</em> della stessa;</li>
    <li>se la richiesta sia o meno stata approvata da tutti i fornitori;</li>
    <li>se la richiesta è valida</li>.
</ul>

Nel momento in cui almeno un fornitore approva la richiesta, l'area della stessa viene visualizzata nella pagina WebGIS: entro la stessa, i dati di osservazioni eventualmente presenti all'interno appaiono alla massima precisione disponibile (dettaglio puntiforme). Inoltre, per ogni <code>fornitore</code> che accetta la richiesta, il sistema mette a disposizione sempre nella pagina di elenco delle richieste un link di download del dataset corrispondente ai dati messi a disposizione entro quell'area dal <code>fornitore</code>. Se tutti i <code>fornitori</code> accettano la richiesta, il sistema restituisce un solo link con il dataset globale entro l'area richiesta pronto per lo scaricamento.

L'utente viene notificato delle varie decisioni prese dai singoli <code>fornitori</code> riguardo la sua richiesta.

Passati dieci giorni dall'invio del form, la richiesta viene automaticamente eliminata, qualsiasi sia il suo <em>status</em>.

{%endblock documentation_detail%}

src/templates/documentation/documentation_gis.html
{% extends 'documentation/documentation_base.html' %}
{% load static %}


{% block documentation_detail %}
<style>
    .button-ol {
        color: white;
        background-color: #E94718;
        border: 1px solid black;
    }
</style>
<h3>Comandi base</h3>
La pagina di consultazione dei dettagli delle osservazioni <em>taxon</em>-specifiche si presenta come un normale WebGIS.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_2.png'%}"></img>
</figure>

Oltre ai comandi di zoom in/out (<strong class="button-ol">+</strong> / <strong class="button-ol">-</strong>) nel pannello in alto a sinistra), alla barra di scala in basso a sinistra e alle informazioni relative ai layer di sfondo visualizzate premendo sul pulsante <strong class="button-ol">i</strong> in basso a destra, si notano due barre degli strumenti entro la mappa. Nel dettaglio:

<ul>
<li>In basso 
<figure>
    <img src="{% static 'site/img/manual/biostream_22.png'%}"></img>
</figure>
con funzionalità, nell'ordine da sinistra a destra:
    <ul>
        <li>spostamento della visuale della mappa</li>
        <li>attivazione dei filtri per i layer delle specie</li>
        <li>zoom all'area del Progetto (area di competenza degli enti <code>gestori</code>)</li>
        <li>modalità schermo intero</li>
        <li>reset della rotazione</li>
        <li>disattivazione della maschera di sfondo</li>
        <li>salvataggio immagine della mappa</li>
    </ul>
</li>

<li>In alto
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_21.png'%}"></img>
</figure>
con funzionalità di ricerca e zoom ad una qualsiasi località (lente) e zoom su un punto cliccato 
</li>
</ul>

<h3>Selettore layer</h3>
In alto a destra è poi disponibile un selettore dei layer: entro questo menu vengono sia visualizzati i layer di sfondo che tutti i layer di specie caricati dall'utente. Di ogni layer l'utente può attivare / disattivare la visualizzazione così come regolarne la trasparenza agendo sullo <em>slider</em>, oppure rimuoverlo del tutto (possibile solo per i layer di specie e per quelli aggiunti tramite trascinamento, come ad esempio i KML). 
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_15.png'%}"></img>
</figure>

<h3>Ricerca <em>taxon</em></h3>
All'esterno della mappa l'utilità più evidente è la barra di ricerca della tassonomia: digitando almeno tre lettere del nome scientifico della specie per la quale si desidera visualizzare i punti di osservazione / campionamento, il sistema restituisce tutti i <em>taxa</em> che corrispondono a quella ricerca, compresi quelli di grado superiore alla specie. Una ricerca per tassonomie superiori a quella specie-specifica restituisce non solo le osservazioni con esattamente quel grado di determinazione tassonomica, ma anche tutte le specie incluse in tale gerarchia.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_3.png'%}"></img>
</figure>
Una volta effettuata la ricerca, il layer della specie viene aggiunto alla mappa cliccando sul nome desiderato.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_6.png'%}"></img>
</figure>
A seconda che l'utente abbia effettuato il login o meno, sulla mappa appaiono:
<ul>
    <li><strong>per qualsiasi utente</strong> un solo layer composto di poligoni esagonali di dimensione prefissata (10<code>km</code> di apotema) che ricoprono regolarmente i punti di segnalazione del <em>taxon</em> selezionato. A seconda che l'utente sia o meno autenticato, l'apotema dell'esagono si ridimensiona in base allo zoom;</li>
    <li><strong>per utenti autenticati</strong> anche il layer delle osservazioni precise: queste vengono visualizzate a seconda dei permessi concessi al'utente come specificato nell'<a href="{% url 'documentation_base' %}">introduzione</a></li>  
</ul>
Il colore prevalente dei vari layer è scelto casualmente dal sistema.

<h3>Filtri</h3>
Cliccando sul pulsante di attivazione dei filtri nella barra degli strumenti principale, si possono impostare dei filtri globali (ovvero, validi per tutti i layer di specie) che agiscono rispetto agli attributi delle osservazioni.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_4.png'%}"></img>
</figure>

<h3>Attributi delle osservazioni</h3>
Per accedere a questi attributi, è sufficiente cliccare su uno degli esagoni sovrapposti ai punti di osservazione: la visualizzazione si sposterà quindi appena sotto la mappa, mostrando i dettagli degli attributi delle osservazioni contenute entro l'esagono selezionato all'interno di una tabella navigabile.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_8.png'%}"></img>
</figure>
Alcuni di questi attributi sono interattivi, ovvero, aprono ulteriori schede che specificano meglio l'informazione selezionata: la disponibilità di queste schede è segnalata dalla presenza sull'informazione di un bottone arancione.
<figure>
    <img class="img-doc-long" src="{% static 'site/img/manual/biostream_9.png'%}"></img>
    <figcaption>Scheda aggiuntiva con informazioni riguardo il dataset di origine per una certa osservazione</figcaption>
</figure>
<figure>
    <img class="img-doc-long" src="{% static 'site/img/manual/biostream_11.png'%}"></img>
    <figcaption>Scheda aggiuntiva con informazioni generali riguardo il taxon selezionato. Questa scheda è raggiungibile anche premendo il bottone <strong class="button-ol">i</strong> a fianco del nome del <em>taxon</em> desiderato entro il pannello dei layer.</figcaption>
</figure>

<h3>URI</h3>
Ogni osservazione è corredata di una URI - <em>Universal Resourse Identifier</em>, ovvero, di una URL che rimanda l'utente ad una pagina separata e specifica di ogni osservazione ove l'utente può visualizzare informazioni aggiuntive riguardo quella stessa osservazione.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_13.png'%}"></img>
</figure>

<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_14.png'%}"></img>
</figure>

<h3 id="layersfondo">Layer di sfondo</h3>
Quasi tutti i layer di sfondo sono interrogabili: al click sulla mappa e con i layer di sfondo attivati, il sistema restituisce appena sotto la vista WebGIS gli attributi corrispondendi all'oggetto cliccato.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_18.png'%}"></img>
</figure>

In particolare, il layer degli Habitat Natura2000 restituisce anche un collegamento al sito "<a href="http://vnr.unipg.it/habitat/">Habitat Italia</a>": cliccando sul codice dell'habitat corrispondente all'oggetto cliccato con il corrispondente layer attivato, viene aperto un popup che visualizza i dettagli di tale habitat come appaiono sul sito di cui sopra.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_19.png'%}"></img>
</figure>

<h3 id="areaquery">Interrogazione per area</h3>
È possibile prescindere dalla ricerca per singola tassonomia ed interrogare il portale affinchè restituisca tutte le informazioni relative ad una certa area richiesta (funzionalità simile a quanto disponibile nella pagina di <a href="{% url 'documentation_checklist'%}">checklist</a>): lo strumento si attiva cliccando sul bottone "Cerca per area disegnata".
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_20.png'%}"></img>
</figure>

Dopo l'attivazione dello strumento, il cui bottone si illumina di verde, l'utente provvede a disegnare un'area non più grande di 10<code>kmq</code> (misura scelta a priori per non sovraccaricare il sistema: è possibile che in futuro tale limite venga aumentato o del tutto rimosso), anche grazie all'aiuto del <em>tooltip</em> che mostra le dimensioni dell'area via via che il disegno prosegue. Per aggiungere punti all'area è sufficiente fare click con il tasto sinistro del mouse: con il click destro si completa invece il disegno, operazione che produce un elenco di tutte le osservazioni di dettaglio disponibili entro l'area. 

L'utente può ripetere l'operazione disegnando una nuova area dopo aver rimosso quella vecchia (tasto "pulisci" attivo nella barra degli strumenti principale), oppure tornare alla modalità normale cliccando nuovamente sul bottone "Cerca per area disegnata": dopo la disattivazione, il simbolo entro il bottone ritorna bianco, e l'utente può utilizzare il WebGIS normalmente.






{%endblock documentation_detail%}

src/templates/documentation/documentation_programmers.html
{% extends 'documentation/documentation_base.html' %}
{% load static %}

{% block documentation_detail %}
{%endblock documentation_detail%}

src/templates/documentation/documentation_usermanager.html
{% extends 'documentation/documentation_base.html' %}
{% load static %}

{% block documentation_detail %}
<h3>Gestione utenti</h3>
Nell'interfaccia di amministrazione (<code>Admin</code> > <code>Utenti</code>) è possibile per gli amministratori di sistema abilitare/disabilitare e soprattutto
assegnare permessi ai singoli utenti registrati a sistema. Il meccanismo è particolarmente utile per dare accesso compartimentato solo a certe parti dell'interfaccia di 
amministrazione, e/o ad abilitare la visualizzazione dei dati di dettaglio senza al contrario dare accesso all'<em>admin</em>.

Per modificare i permessi relativi ad un utente registrato, cliccare sull'indirizzo mail dell'utente interessato tra quelli che appaiono nella lista:
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_34.png'%}"></img>
</figure>
Vi sono svariate opzioni:
    <ul>
        <li>attivare/disattivare una utenza (nel caso di utenza disattiva, il proprietario non riuscirà ad effettuare l'accesso al sistema pur conservando quest'ultimo i suoi dati e le strutture da lui generate);</li>
        <li>assegnare all'utente <strong>privilegi di staff</strong>: questo consente al profilo di accedere all'interfaccia di amministrazione;</li>
        <li>assegnare all'utente <strong>privilegi di amministratore</strong>: l'utente acquisisce pieni poteri sul sistema;</li>
        <li>assegnare all'utente un gruppo di permessi preimpostato, in particolare:
            <ul>
                <li><strong>DATABASE_INGESTOR</strong>: l'utente può inserire nuovi dataset, previa l'attivazioone della flag <em>privilegi di staff</em>;</li>
                <li><strong>READONLY</strong>: l'utente ha privilegi utili esclusivamente a visualizzare le informazioni del portale, al dettaglio puntiforme che gli compete;</li>
                <li><strong>USERS_MANAGER</strong>: l'utente può assegnare permessi ad altri utenti.</li>
            </ul>
            Da notare come ad un utente possono essere assegnati anche gruppi di permessi multipli.
        </li>
        <li>assegnare all'utente permessi di dettaglio (scrittura/modifica/eliminazione/lettura) a seconda della componente del sistema che si vuole abilitare.</li>
    </ul>
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_35.png'%}"></img>
</figure>
Per ulteriore validazione dell'utente, ed in particolare per abilitarlo alla visualizzazione dei dati puntiformi, è necessario validarne la mail e l'istituzione di provenienza: lo si può
fare semplicemente spuntando i relativi campi sul fondo del profilo utente.
<figure>
    <img class="img-doc-wide" src="{% static 'site/img/manual/biostream_36.png'%}"></img>
</figure>



{%endblock documentation_detail%}