src/accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path('password-reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password-reset-confirm')
    # url(
    #    r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
    #    views.PasswordResetConfirmView.as_view(),
    #    name="password-reset-confirm",
    # ),
]

src/map/urls.py
from rest_framework import routers
from django.urls import path
from .api import (
    AreeProtetteCheckListViewSet, AreeProtetteViewSet,ComuniViewSet, ObservationChecklistViewSet,
    ProvinceViewSet, ComuniViewSet, ObservationChecklistDetailedViewSet
)
from .views import AreeAutocomplete, ComuniAutocomplete

router = routers.DefaultRouter()
router.register(r'province', ProvinceViewSet)
router.register(r'comuni', ComuniViewSet)
router.register(r'areeprotette', AreeProtetteViewSet)
router.register(r'aree-protette-check', AreeProtetteCheckListViewSet,basename='aree-protette-check')
router.register(r'observations-taxon-check', ObservationChecklistViewSet,basename='observations-taxon-check')
router.register(r'observations-taxon-detailed-check', ObservationChecklistDetailedViewSet,basename='observations-taxon-detailed-check')


urlpatterns = [    
    path('aree-autocomplete',AreeAutocomplete.as_view(),name="aree-autocomplete"),
    path('comuni-autocomplete/',ComuniAutocomplete.as_view(),name='comuni-autocomplete'),

]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

src/templates/_brandname.html
BioSTREAM

src/templates/_navbar.html
{% load static %}

<div class="it-header-navbar-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg"> <!-- has-megamenu"> --> 
                    <button class="custom-navbar-toggler" type="button" aria-controls="nav10" aria-expanded="false" aria-label="Navigazione" data-bs-toggle="collapse" data-bs-target="#nav10">
                        <svg class="icon">
                            <use xlink:href="{% static 'images/svg/sprite.svg' %}#it-burger"></use>
                        </svg>
                    </button>
                    <div class="collapse navbar-collapsable" id="nav10">
                        <div class="overlay"></div>
                        <div class="close-div sr-only">
                            <button class="btn close-menu" type="button"><span class="it-close"></span>close</button>
                        </div>
                        <div class="menu-wrapper">
                            <ul class="navbar-nav">
								<li class="nav-item {% if active_link == "home" %}active{% endif %}"><a class="nav-link {% if active_link == "home" %}active{% endif %}" href="{% url 'home' %}"><span>Home <i class="fa fa-home" aria-hidden="true"></i></span></a></li>
								<li class="nav-item {% if active_link == "gis" %}active{% endif %}"><a class="nav-link {% if active_link == "gis" %}active{% endif %}" href="{% url 'gis' %}"><span>WebGIS <i class="fa fa-search" aria-hidden="true"></i></span></a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle {% if active_link == "servizi" %}active{% endif %}" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span>Servizi <i class="fa fa-tools" aria-hidden="true"></i></span>
                                        <svg class="icon icon-xs">
                                            <use xlink:href="{% static 'images/svg/sprite.svg' %}#it-expand"></use>
                                        </svg>
                                    </a>
                                    <div class="dropdown-menu">
                                        <div class="link-list-wrapper">
                                            <ul class="link-list">
                                                <li>
                                                    <h3 class="no_toc" id="heading">GIS</h3>
                                                </li>
                                                <li><a class="list-item" href="{% url 'checklist' %}"><span>Checklist</span></a></li>
                                                <li><a class="list-item" href="{% url 'table-specie' %}"><span>Dettaglio specie</span></a></li>
                                                <li><a class="list-item" href="{% url 'table-sic' %}"><span>Dettaglio siti</span></a></li>                                                
                                                <li>
                                                    <h3 class="no_toc" id="heading">DATI</h3>
                                                </li>
                                                <li><a class="list-item" href="{% url 'datarequests-list'%}"><span>Richieste dati</span></a></li>
                                                {% if user.is_superuser %}
                                                <li><a class="list-item" href="{% url 'taxon-nonmatch'%}"><span>Match tassonomico</span></a></li>
                                                {% endif %}
                                                <li><a class="list-item" href="/api"><span>API</span></a></li>

                                                <li>
                                                    <h3 class="no_toc" id="heading">CATALOGHI</h3>
                                                </li>
                                                <li><a class="list-item" href="{% url 'catalogo' %}"><span>Dataset</span></a></li>
                                                <li><a class="list-item" href="{% url 'specie-catalog' %}"><span>Specie</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle {% if active_link == "documentation" %}active{% endif %}" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span>Documentazione <i class="fa fa-file-word-o" aria-hidden="true"></i></span>
                                        <svg class="icon icon-xs">
                                            <use xlink:href="{% static 'images/svg/sprite.svg' %}#it-expand"></use>
                                        </svg>
                                    </a>
                                    <div class="dropdown-menu">
                                        <div class="link-list-wrapper">
                                            <ul class="link-list">
                                                <li><a class="list-item" href="{% url 'documentation_base' %}"><span>Base</span></a></li>
                                                <li><a class="list-item" href="{% url 'documentation_gis' %}"><span>GIS</span></a></li>
                                                <li><a class="list-item" href="{% url 'documentation_checklist' %}"><span>Checklist</span></a></li>
                                                <li><a class="list-item" href="{% url 'documentation_datarequest' %}"><span>Richieste dati</span></a></li>
                                                {% if perms.authtools.can_change_users %}
                                                <li><a class="list-item" href="{% url 'documentation_usermanager' %}"><span>Gestione utenti</span></a></li>
                                                {%endif%}
                                                {% if user.is_staff %}
                                                <li><a class="list-item" href="{% url 'docs_root' %}"><span><em>Sysadmin</em></span></a></li>
                                                {%endif%}
                                            </ul>
                                        </div>
                                    </div>
                                </li>                                                        
								<li class="nav-item {% if active_link == "statuspage" %}active{% endif %}"><a class="nav-link {% if active_link == "statuspage" %}active{% endif %}" href="{% url 'statuspage' %}"><span><em>Status</em> sistema <i class="fa fa-check" aria-hidden="true"></i></span></a></li>
                                <li class="nav-item dropdown">
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>

src/templates/about.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base_nologo.html
{% extends 'bootstrap-italia-base.html' %}

<!-- From app django-sass-processor -->
{% load sass_tags %}

{% load static %}
{% load static %}
{% load thumbnail %}

{% block extra_head %}
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<link rel="stylesheet" href="{% static 'site/css/main.css' %}">
<link rel="stylesheet" href="{% static 'site/css/loader.css'%}" />

<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" />	
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" />
<script src="https://browser.sentry-cdn.com/5.11.1/bundle.min.js" integrity="sha384-r7/ZcDRYpWjCNXLUKk3iuyyyEcDJ+o+3M5CqXP5GUGODYbolXewNHAZLYSJ3ZHcV" crossorigin="anonymous">
</script>
<script>
Sentry.init({ dsn: 'https://5003d94eb4c2490ea0935b45b33b6613@sentry.io/1896862' });
</script>

{% endblock extra_head %}

<!-- Page Title -->
{% block page_title %}
Progetto BioSTREAM
{% endblock page_title %}

<!-- EMpty block for languages -->
{% block header_slim_sub_menu %}
{% endblock header_slim_sub_menu %}

<!-- URL link top left -->
{% block header_slim_org_url %}
http://biostreamportal.net
{% endblock header_slim_org_url %}

<!-- Name top left -->
{% block header_slim_org_name %}
Progetto BioSTREAM
{% endblock header_slim_org_name %}

{% block header_slim_buttons %}
<div class="it-access-top-wrapper">
    {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle profile-menu" data-bs-toggle="dropdown">
                <span class="profile-name-navbar">{{ user.get_full_name|truncatechars:20 }} </span>
                <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />        
		    </a>
		    <ul class="dropdown-menu user-menu" role="menu">
                    {% if user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    {% endif %}                
                    <li><a href="{% url 'profiles:show_self' %}">Profilo</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
            </ul>
        </ul>
    {% else %}
    <a href="{% url 'accounts:login' %}"><button class="btn btn-primary btn-sm" type="button">Login</button></a>
    <a href="{% url 'accounts:signup' %}"><button class="btn btn-primary btn-sm" type="button">Registrati</button></a>
    {% endif %}
</div>
{% endblock header_slim_buttons %}

<!-- Mobile slim_org_name -->
{% block header_slim_mobile_org_name %}
Progetto BioSTREAM
{% endblock header_slim_mobile_org_name %}

<!-- Make empty areas -->
{% block header_mobile_arrow %}{% endblock header_mobile_arrow %}
{% block header_mobile_slim_menu %}{% endblock header_mobile_slim_menu %}

<!-- No upper social -->
{% block header_center_social %}
{% endblock header_center_social %}

<!-- No search -->
{% block header_center_search %}
{% endblock header_center_search %}

<!-- Organization name in Header -->
{% block header_center_org_name %}
{% endblock header_center_org_name %}

<!-- Organization description in Header -->
{% block header_center_org_subname %}
<!--BIO System for Transmission and Retrieval of Environmental Data and Attributes-->
{% endblock header_center_org_subname %}

{% block header_center_logo %}
{% endblock header_center_logo %}

{% block header_slim_top_left %}
{%endblock%}

<!--
-----------------
	MAIN MENU
-----------------
-->
{% block main_menu %}
{% endblock main_menu %}

<!--
---------------
	FOOTER 
---------------
-->

<!-- Logo in Footer -->
{% block footer_logo %}
{% endblock footer_logo %}

<!-- Organization name in Footer -->
{% block footer_org_name %}
{% endblock footer_org_name %}

<!-- Organization name in Footer -->
{% block footer_org_subname %}
{% endblock footer_org_subname %}

{% block centered_container %}
<!-- Loader -->
<div id="overlay">
  <div class="lds-dual-ring"></div>
</div>
{% endblock %}

{% block first_column %}
{% endblock first_column %}
{% block second_column %}
{% endblock second_column %}
{% block third_column %}
{% endblock third_column %}
{% block fourth_column %}
{% endblock fourth_column %}
{% block footer_contacts_section %}
{% endblock footer_contacts_section %}
{% block footer_bottom_content %}
{% endblock footer_bottom_content %}

{% block bottom_scripts %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wnumb/1.2.0/wNumb.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>  
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Remove header-->
    <script>
    $('.it-header-center-wrapper').remove();
	</script>
    <!-- Loader -->
    <script>
    	var loadToggle = function(start) {
		if(start===true) {
			document.getElementById("overlay").style.display = "block";		
		} else {
			document.getElementById("overlay").style.display = "none";			
		}
	};
    </script> 
    <!-- Modal creator -->
    <script>
		var bootModal = function (title, body,not_backdrop) {
			var title = title || "Lorem Ipsum Titolo", body = body || "Lorem Ipsum Corpo", buttons = buttons || [{ Value: "Chiudi", Css: "btn-primary", callback: function (event) { bootModal.close(); } }];
			var getModalStructure = function () {
                var that = this;
                if( typeof id === 'undefined') {
                    that.id = bootModal.id = Math.random();
                } else that.id = id;
				var buttonshtml = "";
				for (var i = 0; i < buttons.length; i++) {
					buttonshtml += "<button type='button' class='btn " + (buttons[i].Css||"") + "' name='btn" + that.id + "'>" + (buttons[i].Value||"Chiudi") + "</button>";
				}
				return "<div class='modal fade' name='dynamiccustommodal' id='" + that.id + "' tabindex='-1' role='dialog' data-backdrop=" + ((typeof not_backdrop != 'undefined') ? false : "'static'") + " data-keyboard='false' aria-labelledby='" + that.id + "Label'><div class='modal-dialog modal-lg'><div class='modal-content'><div class='modal-header'><h4 class='modal-title'>" + title + "</h4><button type='button' class='close modal-white-close' onclick='bootModal.close()'><span aria-hidden='true'>&times;</span></button></div><div class='modal-body'><div class='row'><div class='col-xs-12 col-md-12 col-sm-12 col-lg-12'>" + body + "</div></div></div><div class='modal-footer bg-default'><div class='col-xs-12 col-sm-12 col-lg-12'>" + buttonshtml + "</div></div></div></div></div>";
			}();
			bootModal.delete = function () {
				var modals = document.getElementsByName("dynamiccustommodal");
				if (modals.length > 0) document.body.removeChild(modals[0]);
			};
			bootModal.close = function () {
				$(document.getElementById(bootModal.id)).modal('hide');
				bootModal.delete();
			};    
			this.show = function () {
				bootModal.delete();
				document.body.appendChild($(getModalStructure)[0]);
				var btns = document.querySelectorAll("button[name='btn" + bootModal.id + "']");
				for (var i = 0; i < btns.length; i++) {
					btns[i].addEventListener("click", buttons[i].callback || bootModal.close);
				}
				$(document.getElementById(bootModal.id)).modal('show');
			};
		};
    </script>
    <!-- Exports -->
    <script>
		function download_csv(csv, filename) {
			var csvFile;
			var downloadLink;
			csvFile = new Blob([csv], {type: "text/csv"});
			downloadLink = document.createElement("a");
			downloadLink.download = filename;
			downloadLink.href = window.URL.createObjectURL(csvFile);
			downloadLink.style.display = "none";
			document.body.appendChild(downloadLink);
			downloadLink.click();
		}

		function export_table_to_csv(html, filename) {
			var csv = [];
			var rows = document.querySelectorAll("table tr");
			
			for (var i = 0; i < rows.length; i++) {
				var row = [], cols = rows[i].querySelectorAll("td, th");	
				for (var j = 0; j < cols.length; j++) 
					row.push(cols[j].innerText);
				csv.push(row.join(","));		
			}
			download_csv(csv.join("\n"), filename);
		}

    	var loadToggle = function(start) {
			if(start===true) {
				document.getElementById("overlay").style.display = "block";		
			} else {
				document.getElementById("overlay").style.display = "none";			
			}
		};
    </script>
{% endblock bottom_scripts %}

src/templates/base_old.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-bs-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-bs-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a id="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/status.html
{% extends 'base_nologo.html' %}

{% load static %}

{% block main_menu %}
	{% include "_navbar.html"%}
{% endblock main_menu %}

{% block centered_container %}

<h1>Status servizi</h1>
    </br>
    <ul id="service-status-list">
    </ul>
{% endblock centered_container %}

{% block bottom_scripts %}
	{{ block.super }}
    <script>
        function addElement(item, index) {
        }

        fetch("{% url 'status' %}")
        .then(function (response) { return response.text();})
        .then(function(response) {
            response = JSON.parse(response);

            Object.keys(response).forEach(function(key) {
                $('#service-status-list').append("<li><strong>" + key + "</strong>: " + (((response[key][0]!=undefined) ? response[key][0]["default"]["ok"]: response[key]["ok"]) ? "<button type='button' class='btn btn-primary'> REGOLARMENTE FUNZIONANTE </button>" : "<button type='button' class='btn btn-danger'> OFFLINE </button>") + "</li></br>");
            });            
        }).catch();
    </script>

{% endblock %}