src/data_requests/urls.py
from django.urls import path

from .views import (
    DataRequestsListView,
    DataRequestsCreate, DataRequestsDelete,
    DataRequestFull,extract_and_send_db_via_email
)

urlpatterns = [
     path('list/', DataRequestsListView.as_view(),
          name='datarequests-list'),
     path('list/add/', DataRequestsCreate.as_view(), name='datarequests-add'),
     # richieste non editabili una volta fatte, per ordine
     #path('list/<int:pk>/', DataRequestsUpdate.as_view(),
     #     name='datarequests-update'),
     #<div class="col-sm-10"><a href="{% url 'datarequests-update' datarequest.id%}" class="btn btn-primary">Modifica</a>

     path('list/delete/<int:pk>', DataRequestsDelete.as_view(),
          name='datarequests-delete'),
     path('full-form/', DataRequestFull.as_view(), name='extract_full_form'),                    
     path('extract-full/', extract_and_send_db_via_email, name='extract_full'),          
]

src/map/urls.py
from rest_framework import routers
from django.urls import path
from .api import (
    AreeProtetteCheckListViewSet, AreeProtetteViewSet,ComuniViewSet, ObservationChecklistViewSet,
    ProvinceViewSet, ComuniViewSet, ObservationChecklistDetailedViewSet
)
from .views import AreeAutocomplete, ComuniAutocomplete

router = routers.DefaultRouter()
router.register(r'province', ProvinceViewSet)
router.register(r'comuni', ComuniViewSet)
router.register(r'areeprotette', AreeProtetteViewSet)
router.register(r'aree-protette-check', AreeProtetteCheckListViewSet,basename='aree-protette-check')
router.register(r'observations-taxon-check', ObservationChecklistViewSet,basename='observations-taxon-check')
router.register(r'observations-taxon-detailed-check', ObservationChecklistDetailedViewSet,basename='observations-taxon-detailed-check')


urlpatterns = [    
    path('aree-autocomplete',AreeAutocomplete.as_view(),name="aree-autocomplete"),
    path('comuni-autocomplete/',ComuniAutocomplete.as_view(),name='comuni-autocomplete'),

]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

src/data_requests/models.py
from io import StringIO
from io import BytesIO
import zipfile
import re
import logging

from adminactions.templatetags.actions import verbose_name
from django.conf import settings
from django.core.files import File
from django.utils.timezone import now
from datetime import timedelta
def expiration():
    return now() + timedelta(days=15)

from django_currentuser.middleware import get_current_user
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Q

from django.contrib.gis.db import models
from django.contrib.gis.db.models.functions import Transform
from django.contrib.gis.gdal import DataSource
from django.contrib.gis.geos import Polygon, MultiPolygon

from django.core.exceptions import ValidationError

from biodiv.models import Institution, Observation
from biostream.models import (GeoModel, ShortTextField, TimeStampedModel,
                              UserReferencedModel)
from map.models import Comuni
# a) quando un utente inserisce una richiesta dati, notifica i responsabili degli enti preposti
# 1) crea automaticamente csv con tutti i dati richiesti, invisibili all'utente fino a punto 2)
# 2) quando tutte le richieste di accettazione sono validate, manda un segnale all'utente riguardo l'accettazione, magari con link ai dati
from biostream.utils import convert_to_dataframe
from profiles.models import Profile
from taxon.models import Taxonomy

from django.core.mail import EmailMessage, EmailMultiAlternatives
from biostream.utils import get_or_null,get_admin_url
class DataRequestQuerySet(models.QuerySet):
    def accepted(self):
        acceptances = DataRequestAcceptance.objects.filter(
            data_request=self).values_list('accepted', flat=True)
        if all([x == True for x in acceptances]):
            return self
        else:
            return None

#class DataRequestManager(models.Manager):
#    def get_queryset(self):
        return super().get_queryset().filter(expiration_date>now)
    #def get_queryset(self):
    #    return DataRequestQuerySet(self.model, using=self._db)
    

class DataRequest(UserReferencedModel, TimeStampedModel, GeoModel):
    id = models.AutoField(
        "ID", primary_key=True, db_column='data_requests_id')
    name = ShortTextField('Nome identificativo della richiesta',blank=True,null=True)
    geom = models.MultiPolygonField("Geometria della richiesta", srid=4326,blank=True,null=True)
    description = models.TextField("Motivo della richiesta")
    comune = models.ForeignKey(Comuni,verbose_name="Comune entro il quale si vuole effettuare la richiesta",
        blank=True,null=True,help_text="ATTENZIONE: selezionare un comune ha precedenza rispetto al disegnare / inserire manualmente una geometria!",on_delete=models.SET_NULL)
    habitat_only = models.BooleanField(
        "Richiesti solo i taxa protetti secondo la Direttiva Habitat?", blank=True, null=True)
    #expiration_date = models.DateTimeField(default=expiration,verbose_name='Scade in',blank=True,null=True)
    expired = models.BooleanField("Richiesta scaduta", default=False)
    accepted = models.BooleanField(
        "Richiesta accettata da tutti i Fornitori", default=False)
    geofile = models.FileField("File contenente la geometria",blank=True,null=True,help_text="KML, GeoJSON o GPKG")
    is_blank = models.BooleanField("La richiesta contiene dati rispetto ai parametri impostati?",default=True)
    #objects = DataRequestManager()

    class Meta:
        managed = True
        verbose_name = 'Richiesta dati'
        verbose_name_plural = 'Richieste dati'
        ordering = ['expired', 'id']
        app_label = 'data_requests'

    @property
    def is_accepted(self):
        acceptances = DataRequestAcceptance.objects.filter(
            data_request=self).values_list('accepted', flat=True)
        if all([x == True for x in acceptances]):
            return True
        else:
            return False

    def clean(self):
        super(DataRequest, self).clean()
        if self.comune is None and self.geom is None and self.geofile is None:
            raise ValidationError({
            'geom': ["Deve essere disegnata una geometria, oppure definito un comune, o effettuato l'upload di un file!"],
            'comune': ["Deve essere definito un comune, oppure disegnata una geometria, oppure effettuato l'upload di un file!"],
            'comune': ["Deve essere effettuato l'upload di un file, oppure definito un comune, oppure disegnata una geometria!"],
        })


    def __str__(self):
        return "Richiesta dati dell'utente {} del {}".format(self.modified_by, self.created)

    def get_absolute_url(self):
        return reverse('datarequests-list')

    def save(self, *args, **kwargs):
        """
        Creo automaticamente le richieste di accettazione dati 
        per ogni istituzione che ha dati entro l'area indicata ed
        estraggo i dati della richiesta impacchettandoli in uno .zip
        """

        # Se la richiesta esiste...
        if self.pk:
            # ...ne recupero i dati relativi...
            orig = DataRequest.objects.get(pk=self.pk)
            # ...e se la richiesta ha una geometria ed è accettata, mi fermo qua
            if orig.geom == self.geom:
                if orig.is_accepted:
                    self.accepted = True
                super(DataRequest, self).save(*args, **kwargs)
            # ...altrimenti, se la richiesta non ha una geometria, vuol dire che è stata appena creata...
            else:
                # ... quindi prima di tutto la salvo, eventualmente aggiungendo la geometria del comune...
                if self.comune:
                    geom = self.comune.geom
                    self.geom = self.comune.geom
                elif self.geofile:
                    super(DataRequest, self).save(*args, **kwargs)
                    geom = DataSource(self.geofile.path)
                    self.geom = geom
                else:
                    geom = self.geom
                geom = self.geom
                super(DataRequest, self).save(*args, **kwargs)
                # ...poi compilo i form di accettazione per ogni istituzione che ha dati entro la richiesta
                # ...se l'utente ha selezionato un comune, prendo quello come geometria di riferimento
                # la trasformazione in diversi SRID avviene in automatico: https://docs.djangoproject.com/en/3.2/ref/contrib/gis/tutorial/
                # estraggo i nomi delle istituzioni che hanno dati
                obss = Observation.objects.filter(geom__intersects=geom)
                institutions = Observation.objects.filter(
                    geom__intersects=geom).values_list('dataorigin__institution__id').distinct()
                # se la richiesta non contiene dati, mi fermo
                if not institutions:
                    self.is_blank = True
                    super(DataRequest, self).save(*args, **kwargs)                    
                else:
                    if self.habitat_only and not obss.filter(
                        Q(taxon__taxonprotection__habitat_ap_2=True) | Q(taxon__taxonprotection__habitat_ap_2_prior=True) | Q(taxon__taxonprotection__habitat_ap_4=True) | Q(taxon__taxonprotection__habitat_ap_5=True)
                    ):
                        self.is_blank = True
                        super(DataRequest, self).save(*args, **kwargs)                    
                    else:
                        # se c'erano già istituzioni, vuol dire che l'utente ha cambiato geometria: elimino quindi le vecchie richieste di accettazione
                        DataRequestAcceptance.objects.filter(
                            data_request=DataRequest.objects.filter(id=self.id)[0]).delete()

                        ###
                        # Per ogni istituzione creo il set di dati appartenente e lo rendo disponibile come file
                        # in modo che il validatore possa rapidamente capire che cosa viene richiesto
                        ###
                        # rimuovo i campi che non mi interessano
                        for institution in institutions:
                            obs = obss.filter(dataorigin__institution__id__in=institution).defer('geom')
                            if self.habitat_only:
                                obs = obs.filter(
                                    Q(taxon__taxonprotection__habitat_ap_2=True) | 
                                    Q(taxon__taxonprotection__habitat_ap_2_prior=True) |
                                    Q(taxon__taxonprotection__habitat_ap_4=True) |
                                    Q(taxon__taxonprotection__habitat_ap_5=True)
                                )
                            # se dopo l'eventuale filtro la richiesta ha ancora osservazioni, proseguo
                            if obs:
                                # nei queryset non posso aggiungere ai valori risultati di metodi. devo quindi
                                # appenderli manualmente, e dato che le queryset sono dizionari...
                                for ob in obs:
                                    ob.lat = ob.latitude_wgs84
                                    ob.lon = ob.longitude_wgs84

src/data_requests/forms.py
from django import forms
from .models import DataRequest
from leaflet.forms.widgets import LeafletWidget
from dal import autocomplete

class DataRequestForm(forms.ModelForm):
    """
    Form raggiungibile dal profilo dell'utente utile
    ad inviare richieste di dati precisi.

    .. image:: ../../_static/manual/biostream_25.png
        :width: 400
        :alt: Immagine del form di richiesta dati 
    """
    class Meta:
        model = DataRequest
        fields = ["name","geom","comune","description", "habitat_only"] # "geofile",
        widgets = {
            'comune': autocomplete.ModelSelect2(url='comuni-autocomplete'),
            'geom': LeafletWidget(
                attrs={'map_width': '100%', 'map_height': '300'  # ,'settings_overrides': {
                       # 'DEFAULT_CENTER': (6.0, 45.0),
                       # }
                       },
            )
        }

src/data_requests/views.py
from __future__ import unicode_literals
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpRequest, JsonResponse
from biodiv.models import Observation
from biostream.tasks import export_data_to_excel

import json
from biostream.forms import AjaxableResponseMixin

from .forms import DataRequestForm
from .models import DataRequest

from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView


class DataRequestsListView(LoginRequiredMixin, ListView):
    """
    Richieste dati precisi effettuate dall'utente non di staff
    """
    model = DataRequest

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_user'] = self.request.user
        return context

    def get_queryset(self):
        return DataRequest.objects.filter(created_by=self.request.user)


class DataRequestsCreate(AjaxableResponseMixin, CreateView):
    """
    Crea una nuova richiesta di dati precisi
    """
    model = DataRequest
    form_class = DataRequestForm
    #fields = ['geom', 'description', 'habitat_only']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_user'] = self.request.user
        return context


class DataRequestsUpdate(AjaxableResponseMixin, UpdateView):
    """
    Aggiorna una richiesta di dati precisi per utente non di staff
    """
    model = DataRequest
    form_class = DataRequestForm
    #fields = ['geom', 'description', 'habitat_only']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_user'] = self.request.user
        return context


class DataRequestsDelete(DeleteView):
    """
    Rimuove una richiesta di dati precisi
    """
    model = DataRequest
    success_url = reverse_lazy('datarequests-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_user'] = self.request.user
        return context

def extract_and_send_db_via_email(request: HttpRequest) -> JsonResponse:
    """Handle the post requests for sending emails."""
    if request.method == 'POST':
        request_data = json.loads(request.body)
        email = request_data['userEmail']
        typ = request_data['extractionType']
        
        export_data_to_excel.delay(email,typ)
        return JsonResponse({'message': "Dati in estrazione: attendi l'arrivo della mail"}, status=200)
    return JsonResponse({'message': "Errore nell'estrazione! Contatta l'amministratore di sistema"}, status=500)

class DataRequestFull(TemplateView):
    template_name = "datarequest_full_form.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_user'] = self.request.user
        return context    

src/data_requests/templates/data_requests/datarequest_base.html
{% extends "base.html" %}

{% load static %}

{% load thumbnail %}

{% load leaflet_tags  %}
{% load geojson_tags %}

{% block extra_head %}
  {{ block.super }}
    {% leaflet_js plugins="forms"%}
    {% leaflet_css plugins="forms"%}
    <link rel="stylesheet" href="{% static 'site/css/loader.css'%}" />
    <style>
        .container {
            max-width: 1600px;
        }
    </style>
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}" type="text/javascript"></script>
{% endblock extra_head %}


{% block main_menu %}
    {% include "_navbar.html" %}
{% endblock main_menu %}

{% block title %}{{ block.super }}Richieste dati{% endblock %}

{% block centered_container %}
<!-- Loader -->
<div id="overlay" style="z-index:10000;">
  <div class="lds-dual-ring"></div>
</div>
<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }} - richieste dati</h1>
      <a href="{% url 'profiles:show_self' %}" class="btn btn-info">Torna al profilo</a>
      {%block mainlink%}<a href="{% url 'datarequests-add' %}" class="btn btn-primary">Nuova richiesta</a>{%endblock mainlink%}

    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-12">
      <div class="panel panel-default">
        {% block request_detail %}
        {% endblock request_detail %}
      </div>
    </div>
  </div>
</div>

{% endblock centered_container %}

src/data_requests/templates/data_requests/datarequest_confirm_delete.html
{% extends "data_requests/datarequest_base.html" %}

{% load crispy_forms_tags %}

{% block extra_head %}
  {{ block.super }}
  <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
	<link rel="stylesheet" href="https://openlayers.org/en/latest/css/ol.css" />
{% endblock extra_head %}

{%block mainlink%}<a href="{% url 'datarequests-list' %}" class="btn btn-info">Torna alle richieste</a>{%endblock mainlink%}


{% block title %}{{ block.super }}Richieste dati{% endblock %}

<form method="post">
    {% csrf_token %}
    <p>Sei sicur* di voler rimuovere la richiesta?</p>
    <input type="submit" value="Conferma">
</form>

src/data_requests/templates/data_requests/datarequest_form.html
{% extends "data_requests/datarequest_base.html" %}
{% load static %}
{% load leaflet_tags %}
{% load geojson_tags %}
{% load crispy_forms_tags%}

{% block extra_head %}
  {{ block.super }}
  {{ form.media }}
  <style>
  .select2-container--default .select2-results__option--highlighted[aria-selected] {
    background-color: #E23A1A;
  }
  textarea.form-control {
    max-height: 5em;
  }  
  </style>  
    <script>
    $(document).on("submit","form", function () {
      loadToggle(true);
    });  
    </script>
    <script>
    var map;
    $(window).on('map:init', function(e) {
      map = e.originalEvent.detail.map;
    });
  function getData() {
    return new Promise((resolve, reject) => {
      $.ajax({
        url: "https://biostreamportal.net/static/json/mask_4326.geojson",
        type: 'GET',
        datatype:'json',
        success: function (data) {
          resolve(data)
        },
        error: function (error) {
          reject(error)
        },
      })
    })
  };
</script>
{% endblock extra_head %}

{%block mainlink%}<a href="{% url 'datarequests-list' %}" class="btn btn-info">Torna alle richieste</a>{%endblock mainlink%}

{% block title %}{{ block.super }}Richiesta dati{% endblock %}

{% block request_detail %}
<div class="row">
  <div class="col-1"></div>
    <div class="col-9">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Invia richiesta">
    </form>
    </div>
  <div class="col-2"></div>
</div>
{% endblock request_detail %}

{% block bottom_scripts%}
  {{block.super}}
	<script type="text/javascript" src="{% static 'site/js/select2.js' %}"></script>

  <!-- LEAFLET MASK-->
  <script>
		function getJson(url) {
			return JSON.parse($.ajax({
				type: 'GET',
				url: url,
				dataType: 'json',
				global: false,
				async: false,
				success: function (data) {
					return data;	
				}
			}).responseText);
		};  
L.Mask = L.Rectangle.extend({
	options: {
		stroke: false,
		color: '#333',
		fillOpacity: 0.5,
		clickable: true,

		outerBounds: new L.LatLngBounds([-90, -360], [90, 360])
	},

	initialize: function (latLngBounds, options) {
		L.Polygon.prototype.initialize.call(this, [this._boundsToLatLngs(this.options.outerBounds), this._boundsToLatLngs(latLngBounds)], options);				
	},

	getLatLngs: function () {
		return this._holes[0];
	},

	setLatLngs: function (latlngs) {
		this._holes[0] = this._convertLatLngs(latlngs);
		return this.redraw();
	},

	setBounds: function (latLngBounds) {
		this._holes[0] = this._boundsToLatLngs(latLngBounds);
		return this.redraw();
	}

});

L.mask = function (latLngBounds, options) {
	return new L.Mask(latLngBounds, options);
};


if (L.Draw && L.Draw.SimpleShape) {

	L.Draw.Mask = L.Draw.SimpleShape.extend({
		statics: {
			TYPE: 'mask'
		},

		options: {
			shapeOptions: {
				stroke: false,
				color: '#333',
				fillOpacity: 0.5,
				clickable: true
			}
		},

		initialize: function (map, options) {
			this.type = L.Draw.Mask.TYPE;
			this._initialLabelText = 'Clicca e trascina per creare la maschera';
			L.Draw.SimpleShape.prototype.initialize.call(this, map, options);
		},

		_drawShape: function (latlng) {
			if (!this._shape) {
				this._shape = new L.Mask(new L.LatLngBounds(this._startLatLng, latlng), this.options.shapeOptions);
				this._map.addLayer(this._shape);
			} else {
				this._shape.setBounds(new L.LatLngBounds(this._startLatLng, latlng));
			}
		},

		_fireCreatedEvent: function () {
			var mask = new L.Mask(this._shape.getBounds(), this.options.shapeOptions);
			L.Draw.SimpleShape.prototype._fireCreatedEvent.call(this, mask);
		}
	});

}
</script>
<script>
  var dat;
  getData().then((data) => {
    dat = JSON.parse(data);
    var coordinates = dat.features[0].geometry.coordinates[0][0];
    var latLngs = [];
    for (i=0; i<coordinates.length; i++) {
        latLngs.push(new L.LatLng(coordinates[i][1], coordinates[i][0]));
    }

    L.mask(latLngs).addTo(map);

    var options = {
      style: function (feature) {
        return {
          "color": "#E23A1A",
          "weight": 2,
          "opacity": 1,
        };
      }
    }; 
    new L.geoJson(dat.features[0],options).addTo(map);
    map.fitBounds(L.geoJson(dat.features[0]).getBounds()); 
  });  

</script>
<script>
  $('#id_comune').select2({
    placeholder: "Digita il nome di un comune...",
    language: 'it',
    ajax: {
      url: '{% url "comuni-autocomplete" %}',
      dataType: 'json'
    }
  });
</script>
{%endblock%}

src/data_requests/templates/data_requests/datarequest_list.html
{% extends "data_requests/datarequest_base.html" %}
{% load leaflet_tags  %}
{% load geojson_tags %}

{% block title %}{{ block.super }}Richieste dati - vista{% endblock %}

{%block mainlink%}<a href="{% url 'datarequests-add' %}" class="btn btn-primary">Nuova richiesta</a>
{% if user.is_superuser%}
<a href="{% url 'extract_full_form' %}" class="btn btn-primary">Richiedi tutti i dati</a>
{% endif %}
{%endblock mainlink%}
{% block request_detail %}
<ul class="list-group">
{% for datarequest in object_list %}
    <li class="list-group-item"><span class="pull-left"><strong>{{ datarequest.created|date }}</strong> - {%if datarequest.name %}{{datarequest.name}}{% else %}{{ datarequest.description }}{%endif%}</span><span class="pull-right">Approvata da tutti i Fornitori: {%if datarequest.is_accepted %}<i class="fas fa-check-circle" title="Richiesta approvata"></i>{%else%}<i class="fas fa-times-circle" title="Richiesta rifiutata"></i>{%endif%} | Valida: {%if datarequest.expired %}<i class="fas fa-times-circle" title="Richiesta decaduta"></i>{%else%}<i class="fas fa-check-circle" title="Richiesta valida"></i>{%endif%}</span>
    </li>
    <div id="map_request_{{datarequest.id}}" class="leaflet-container-default"></div>
    <ul class="list-group">
      <li class="list-group-item">
      <strong>Fornitori che devono approvare la richiesta</strong>
      </li>
    {% for datarequest_acceptance in datarequest.datarequestacceptance_set.all %}
      <li class="list-group-item">
      <span class="pull-left"><em>{{datarequest_acceptance.institution}}</em></span><span class="pull-right">Approvata: {%if datarequest_acceptance.accepted %}<i class="fas fa-check-circle" title="Richiesta approvata"></i>{%else%}<i class="fas fa-times-circle" title="Richiesta rifiutata"></i>{%endif%}</span></br><p>Motivazione: {%if datarequest_acceptance.motivation%}{{datarequest_acceptance.motivation|safe}}{%else%}Non espressa{%endif%}</p>
      {% if datarequest_acceptance.accepted%}
      <span class="pull-left"><a href="{{datarequest_acceptance.dataset.url}}">Scarica il dataset</a></span>
      {%endif%}
      </li>
    {%endfor%}
    </ul>
    <script type="text/javascript">
    (function () {
        function loadmap{{datarequest.id}}() {
            var djoptions = {"srid": null, "extent": null, "center": [46.5377684,12.1342377], "zoom": null, "minzoom": 7, "maxzoom": 12, "layers": [["OSM", "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", "\u00a9 Collaboratori <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a>"]], "overlays": [], "attributionprefix": null, "scale": "metric", "minimap": false},
                options = {djoptions: djoptions, initfunc: loadmap{{datarequest.id}},
                          globals: false},
                map = L.Map.djangoMap('map_request_{{datarequest.id}}', options);
                L.geoJson(
                  {{datarequest.geom|geojsonfeature|safe}},
                  {
                    style: {
                    fillColor: '#E94718',
                    weight: 2,
                    opacity: 1,
                    color: '#E94718',
                    fillOpacity: 0.2
                  }
                }).addTo(map);
        }
        var loadevents = ["load"];
        if (loadevents.length === 0) loadmap{{datarequest.id}}();
        else if (window.addEventListener) for (var i=0; i<loadevents.length; i++) window.addEventListener(loadevents[i], loadmap{{datarequest.id}}, false);
        else if (window.jQuery) jQuery(window).on(loadevents.join(' '), loadmap{{datarequest.id}});
    })();
    </script>
    </br>
    <form id="deleteform{{datarequest.id}}" style="visibility:hidden;" method="POST" action="{% url "datarequests-delete" datarequest.id%}">
      {% csrf_token %}<input type="submit">
    </form>
    <div class="row">
    <button class="btn btn-warning" form="deleteform{{datarequest.id}}" value="Rimuovi">Rimuovi</button>    
    <!--<a href="{% url 'datarequests-delete' datarequest.id %}" class="btn btn-warning">Elimina</a>-->
    </div>
    </div>
{% empty %}
    <li class="list-group-item"><span class="pull-left">Nessuna richiesta dati presente</span></li>
{% endfor %}
</ul>      
{% endblock request_detail %}